// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOFType-0]
	_ = x[IntegerType-1]
	_ = x[BooleanType-2]
	_ = x[StringLiteralType-3]
	_ = x[OpenParenType-4]
	_ = x[CloseParenType-5]
	_ = x[OpenBraceType-6]
	_ = x[CloseBraceType-7]
	_ = x[OpenBracketType-8]
	_ = x[CloseBracketType-9]
	_ = x[VarDeclType-10]
	_ = x[SemicolonType-11]
	_ = x[IdentifierType-12]
	_ = x[OperatorType-13]
	_ = x[FnDefType-14]
	_ = x[ReturnType-15]
	_ = x[CommaType-16]
	_ = x[StubDefType-17]
	_ = x[ExportedType-18]
	_ = x[StructDefType-19]
	_ = x[ColonType-20]
	_ = x[IfType-21]
	_ = x[ElseType-22]
	_ = x[WhileType-23]
}

const _TokenType_name = "EOFTypeIntegerTypeBooleanTypeStringLiteralTypeOpenParenTypeCloseParenTypeOpenBraceTypeCloseBraceTypeOpenBracketTypeCloseBracketTypeVarDeclTypeSemicolonTypeIdentifierTypeOperatorTypeFnDefTypeReturnTypeCommaTypeStubDefTypeExportedTypeStructDefTypeColonTypeIfTypeElseTypeWhileType"

var _TokenType_index = [...]uint16{0, 7, 18, 29, 46, 59, 73, 86, 100, 115, 131, 142, 155, 169, 181, 190, 200, 209, 220, 232, 245, 254, 260, 268, 277}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
