// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInvalid-0]
	_ = x[KindBool-1]
	_ = x[KindInt-2]
	_ = x[KindString-3]
	_ = x[KindStruct-4]
}

const _Kind_name = "KindInvalidKindBoolKindIntKindStringKindStruct"

var _Kind_index = [...]uint8{0, 11, 19, 26, 36, 46}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
