// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOFType-0]
	_ = x[IntegerType-1]
	_ = x[BooleanType-2]
	_ = x[StringLiteralType-3]
	_ = x[OpenParenType-4]
	_ = x[CloseParenType-5]
	_ = x[OpenBraceType-6]
	_ = x[CloseBraceType-7]
	_ = x[VarDeclType-8]
	_ = x[TypeType-9]
	_ = x[SemicolonType-10]
	_ = x[IdentifierType-11]
	_ = x[OperatorType-12]
	_ = x[FnDefType-13]
	_ = x[ReturnType-14]
	_ = x[CommaType-15]
	_ = x[StubDefType-16]
	_ = x[ExportedType-17]
	_ = x[StructDefType-18]
	_ = x[ColonType-19]
	_ = x[IfType-20]
	_ = x[ElseType-21]
	_ = x[WhileType-22]
}

const _TokenType_name = "EOFTypeIntegerTypeBooleanTypeStringLiteralTypeOpenParenTypeCloseParenTypeOpenBraceTypeCloseBraceTypeVarDeclTypeTypeTypeSemicolonTypeIdentifierTypeOperatorTypeFnDefTypeReturnTypeCommaTypeStubDefTypeExportedTypeStructDefTypeColonTypeIfTypeElseTypeWhileType"

var _TokenType_index = [...]uint8{0, 7, 18, 29, 46, 59, 73, 86, 100, 111, 119, 132, 146, 158, 167, 177, 186, 197, 209, 222, 231, 237, 245, 254}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
