package compiler

import (
	"encoding/binary"
	"fmt"
	"leoscript/parser"
	"leoscript/types"
	"slices"
)

// The opcodes generated by the compiler
// A number in parentheses in the description indicates a number of parameters that the opcode takes, all 8 bytes long.
// These parameters are later referenced as p(n) in the description.
// A number in parentheses in the description indicates a number of parameters that the opcode takes, all 8 bytes long.
// These parameters are later referenced as p(n) in the description.
const (
	// (1)
	// Push p1 onto the stack
	// Push p1 onto the stack
	OpPush byte = iota + 1
	OpAdd
	OpSub
	OpMul
	OpDiv
	// (1)
	// Store the value at p1 offset from the stack frame base
	// This is used for local variables in functions
	OpStore
	// (1)
	// Load the variable at p1 offset from the stack frame base
	// This is used for local variables in functions
	OpLoad
	// (1)
	// Load the variable at p1 offset from the absolute base of the variable stack
	// This is used for global variables
	OpLoadGlobal
	OpReturn
	OpCall
	// (1)
	// Set the program counter to p1
	OpJump
	// (1)
	// Set the program counter to p1 if the top of the stack is 0
	OpJumpIfFalse
	OpEq
	OpLt
	OpGt
	OpLte
	OpGte
	OpAnd
	OpOr
	// (1)
	// Store the value at location p1 counted from the absolute base of the variable stack
	OpStoreGlobal
	OpInvokeStub
)

func Compile(p *parser.Program) *Executable {
	c := &compiler{
		md:   new(Metadata),
		code: make([]byte, 0),
		globalScope: &scopeContext{
			stackAllocs:        make(map[string]variable),
			currentStackOffset: 0,
		},
		functions: make(map[string]uint64),
	}

	for _, stub := range p.StubDefs {
		c.compileStubDef(stub)
	}

	// Compile the initialization code required for the program
	for _, stmt := range p.VarDecls {
		c.code = append(c.code, c.compileStatement(stmt, c.globalScope, 0)...)
	}
	// The initialization code is followed by a return to have the VM break out of its execution, allowing it to start acception external invokations.
	c.code = append(c.code, OpReturn) // Add a return at the end of the program

	for _, fnDef := range p.FnDefs {
		c.functions[fnDef.Name] = uint64(len(c.code))
		c.code = append(c.code, c.compileFnDef(fnDef)...)
	}

	for _, fn := range c.unresolvedFunctions {
		start, ok := c.functions[fn.name]
		if !ok {
			panic(fmt.Sprintf("unresolved function %s not found in functions map", fn.name))
		}
		// Replace the placeholder offset with the actual start instruction of the function
		binary.BigEndian.PutUint64(c.code[fn.placeholderOffset:], start)
	}

	return &Executable{
		md:   c.md,
		code: c.code,
	}
}

type Executable struct {
	md   *Metadata
	code []byte
}

func (e *Executable) Marshal() []byte {
	return append(e.md.Marshal(), e.code...)
}

func (e *Executable) Metadata() *Metadata {
	return e.md
}

func (e *Executable) Code() []byte {
	return e.code
}

func (e *Executable) Unmarshal(raw []byte) error {
	if len(raw) < 8 {
		return fmt.Errorf("raw executable is too short")
	}

	e.md = new(Metadata)

	mdSize := binary.BigEndian.Uint64(raw[:8])
	if err := e.md.Unmarshal(raw[0 : mdSize+8]); err != nil {
		return fmt.Errorf("unmarshalling metadata: %w", err)
	}

	e.code = raw[mdSize+8:]
	return nil
}

type scopeContext struct {
	parent *scopeContext
	// The stack offsets for each variable allocated on the stack
	stackAllocs map[string]variable
	// The current stack offset for the next variable to be allocated
	currentStackOffset uint64
}

// allocateVariable stores the details of a variable in the current scope, making room for it on the stack.
//
// A virtualVariable is a variable that is not a base variable but instead is just a name for a region of memory.
// An example is for a struct. The fields are the actual variables, the name of the struct-variable is a name for the entire region of memory covering all of the fields.
func (sc *scopeContext) allocateVariable(name string, size uint64, virtualVariable bool) []byte {
	if _, exists := sc.stackAllocs[name]; exists {
		panic(fmt.Sprintf("variable %s already exists in scope", name))
	}

	sc.stackAllocs[name] = variable{
		stackOffset: sc.currentStackOffset,
		size:        size,
	}

	// The instructions required for storing the variable
	var storeInstructions []byte

	// A virtual variable does not get stored on the stack and does therefore not require any instructions nor stack space.
	if !virtualVariable {
		if sc.parent == nil {
			storeInstructions = append(storeInstructions, OpStoreGlobal)
		} else {
			storeInstructions = append(storeInstructions, OpStore)
		}
		storeInstructions = binary.BigEndian.AppendUint64(storeInstructions, sc.currentStackOffset)

		sc.currentStackOffset += 8
	}

	return storeInstructions
}

func (sc *scopeContext) allocateForType(name string, t types.Type) []byte {
	switch t := t.(type) {
	case *types.Struct:
		_ = sc.allocateVariable(name, t.Size(), true)

		var bytes []byte
		// Allocate space for the struct fields
		for _, field := range t.Fields {
			bytes = append(bytes, sc.allocateForType(fmt.Sprintf("%s.%s", name, field.Name), field.Type)...)
		}
		return bytes
	default:
		return sc.allocateVariable(name, t.Size(), false)
	}
}

// Resolve a declared variable and a bool indicating if it came from the global scope.
func (sc *scopeContext) getVariable(name string) (v variable, isGlobal bool) {
	v, ok := sc.stackAllocs[name]
	if ok {
		// If there is no parent scope, we are at the global scope.
		if sc.parent == nil {
			return v, true
		}

		return v, false
	}

	if sc.parent != nil {
		return sc.parent.getVariable(name)
	}

	panic("variable not found in scope: " + name)
}

type variable struct {
	stackOffset uint64
	size        uint64
}

type compiler struct {
	md   *Metadata
	code []byte

	// A mapping for the start-instruction of each function
	functions map[string]uint64

	globalScope *scopeContext

	unresolvedFunctions []unresolvedFunction

	// The names of the stubs that are defined in the program
	stubs []compiledStub
}

type compiledStub struct {
	name string
	// The number assigned to the stub.
	// This is used to identify the stub when it is invoked.
	// It is not the same as the offset in the code, but rather an index in
	// the list of stubs.
	number int
}

// unresolvedFunction is used to track a function call that has not yet been compiled and therefore does not have a start instruction.
type unresolvedFunction struct {
	name              string
	placeholderOffset uint64 // The offset in the code where the function call is made
}

func CompileStatement(stmt parser.Statement) []byte {
	c := &compiler{
		md:          new(Metadata),
		code:        make([]byte, 0),
		globalScope: nil,
		functions:   make(map[string]uint64),
	}
	c.code = append(c.code, c.compileStatement(stmt, &scopeContext{
		stackAllocs:        make(map[string]variable),
		currentStackOffset: 0,
	}, 0)...)
	return c.code
}

func (c *compiler) compileStatement(stmt parser.Statement, sc *scopeContext, pendingBytes int) []byte {
	var bytes []byte // TODO: Possible optimization to pre-allocate the size of bytes based on the expected size of the type of stmt

	switch stmt := stmt.(type) {
	case parser.IntegerLiteral:
		bytes = append(bytes, OpPush)
		bytes = binary.BigEndian.AppendUint64(bytes, uint64(stmt.Value))
	case parser.BooleanLiteral:
		bytes = append(bytes, OpPush)
		if stmt.Value {
			bytes = binary.BigEndian.AppendUint64(bytes, 1) // true
		} else {
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // false
		}
	case parser.StructLiteral:
		for _, field := range stmt.Fields {
			bytes = append(bytes, c.compileStatement(field.Value, sc, 0)...)
		}
	case parser.VoidLiteral:
		// No operation needed for void literals
	case parser.UnaryExpression:
		switch stmt.Op {
		case "-":
			bytes = append(bytes, OpPush)
			bytes = binary.BigEndian.AppendUint64(bytes, 0)

			bytes = append(bytes, OpPush)
			expr := c.compileStatement(stmt.Expression, sc, 0)
			bytes = append(bytes, expr...)

			bytes = append(bytes, OpSub)
		case "!":
			expr := c.compileStatement(stmt.Expression, sc, 0)
			bytes = append(bytes, expr...)
			bytes = append(bytes, OpPush)
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // Push false
			bytes = append(bytes, OpEq)                     // Negate the result of equality
		default:
			panic("unsupported unary operator: " + stmt.Op)
		}
	case parser.BinaryExpression:
		left := c.compileStatement(stmt.Left, sc, 0)
		right := c.compileStatement(stmt.Right, sc, 0)

		bytes = append(bytes, left...)
		bytes = append(bytes, right...)

		switch stmt.Op {
		case "+":
			bytes = append(bytes, OpAdd)
		case "-":
			bytes = append(bytes, OpSub)
		case "*":
			bytes = append(bytes, OpMul)
		case "/":
			bytes = append(bytes, OpDiv)
		case "==":
			bytes = append(bytes, OpEq)
		case "<":
			bytes = append(bytes, OpLt)
		case ">":
			bytes = append(bytes, OpGt)
		case "<=":
			bytes = append(bytes, OpLte)
		case ">=":
			bytes = append(bytes, OpGte)
		case "!=":
			// For !=, we can use the equality operator and negate the result
			bytes = append(bytes, OpEq)
			bytes = append(bytes, OpPush)
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // Push false
			bytes = append(bytes, OpEq)                     // Negate the result of equality
		case "&&": // TODO: Short-circuit evaluation
			bytes = append(bytes, OpAnd)
		case "||": // TODO: Short-circuit evaluation
			bytes = append(bytes, OpOr)
		default:
			panic("unsupported binary operator: " + stmt.Op)
		}
	case parser.VarDecl:
		if stmt.Type.Size()%8 != 0 {
			panic("variable size must be a multiple of 8")
		}
		// The code required to compute the value of the variable.
		val := c.compileStatement(stmt.Value, sc, 0)

		bytes = append(bytes, val...)
		bytes = append(bytes, sc.allocateForType(stmt.Name, stmt.Type)...)

		if stmt.Exported {
			c.recordExportedVariable(stmt)
		}

	case parser.VarIdentifier:
		v, isGlobal := sc.getVariable(stmt.Name)
		var loadOp byte
		if isGlobal {
			loadOp = OpLoadGlobal
		} else {
			loadOp = OpLoad
		}

		for n := range v.size / 8 {
			bytes = append(bytes, loadOp)
			bytes = binary.BigEndian.AppendUint64(bytes, v.stackOffset+n*8)
		}

	case parser.Return:
		if stmt.Value != nil {
			val := c.compileStatement(stmt.Value, sc, 0)
			bytes = append(bytes, val...)
		}
		bytes = append(bytes, OpReturn)
	case parser.Call:
		// Compile the function call arguments
		for _, arg := range stmt.Args {
			argBytes := c.compileStatement(arg, sc, len(bytes))
			bytes = append(bytes, argBytes...)
		}

		// If the function is a stub, instead of calling it, we invoke the stub
		i := slices.IndexFunc(c.stubs, func(s compiledStub) bool {
			return s.name == stmt.Name
		})
		if i != -1 {
			bytes = append(bytes, OpInvokeStub)
			bytes = binary.BigEndian.AppendUint64(bytes, uint64(c.stubs[i].number))
			return bytes
		}

		//
		// Not a stub, do a regular call
		//

		bytes = append(bytes, OpCall)

		// Call the function
		start, ok := c.functions[stmt.Name]
		if ok {
			bytes = binary.BigEndian.AppendUint64(bytes, start)
		} else {
			// If the function is not defined yet, we need to add a placeholder for it
			c.unresolvedFunctions = append(c.unresolvedFunctions, unresolvedFunction{
				name:              stmt.Name,
				placeholderOffset: uint64(len(c.code) + len(bytes)),
			})
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // Placeholder for the function call
		}
	case parser.If:
		bytes = c.compileIf(stmt, sc, pendingBytes)
	case parser.Assignment:
		// Compile the value to assign
		val := c.compileStatement(stmt.Value, sc, 0)
		bytes = append(bytes, val...)

		// Find the variable to assign to
		v, isGlobal := sc.getVariable(stmt.Name)

		var storeOp byte
		if isGlobal {
			storeOp = OpStoreGlobal
		} else {
			storeOp = OpStore
		}

		for n := range v.size / 8 {
			bytes = append(bytes, storeOp)
			bytes = binary.BigEndian.AppendUint64(bytes, v.stackOffset+n*8)
		}

	default:
		panic(fmt.Sprintf("unsupported statement type: %T", stmt))
	}

	return bytes
}

func (c *compiler) compileIf(ifStmt parser.If, sc *scopeContext, pendingBytes int) []byte {
	var bytes []byte
	// Compile the condition
	cond := c.compileStatement(ifStmt.Cond, sc, 0)
	bytes = append(bytes, cond...)

	// Compile the true branch
	var trueBranch []byte
	for _, trueStmt := range ifStmt.Then {
		subStack := &scopeContext{
			parent:             sc,
			stackAllocs:        make(map[string]variable),
			currentStackOffset: sc.currentStackOffset,
		}

		trueBranch = append(trueBranch, c.compileStatement(trueStmt, subStack, len(bytes))...)
	}

	var elseBranch []byte
	for _, elseStmt := range ifStmt.Else {
		subStack := &scopeContext{
			parent:             sc,
			stackAllocs:        make(map[string]variable),
			currentStackOffset: sc.currentStackOffset,
		}

		elseBranch = append(elseBranch, c.compileStatement(elseStmt, subStack, len(bytes))...)
	}

	bytes = append(bytes, OpJumpIfFalse)

	// The offset to jump to if the condition is false
	var falseOffset uint64
	if len(elseBranch) > 0 {
		// If there is an else branch, we need to jump to it if the condition is false
		falseOffset = uint64(len(c.code) + pendingBytes + len(bytes) + len(trueBranch) + 8) // +8 for the size of the jump location itself
		bytes = binary.BigEndian.AppendUint64(bytes, falseOffset)
	} else {
		// If there is no else branch, we just jump over the true branch
		falseOffset = uint64(len(c.code) + pendingBytes + len(bytes) + len(trueBranch) + 8) // +8 for the size of the jump location itself
		bytes = binary.BigEndian.AppendUint64(bytes, falseOffset)
	}

	bytes = append(bytes, trueBranch...)

	if len(elseBranch) > 0 {
		// If there is an else branch, we need to jump over it after the true branch
		bytes = append(bytes, OpJump)
		// The offset to jump to after the true branch
		bytes = binary.BigEndian.AppendUint64(bytes, uint64(len(c.code)+pendingBytes+len(bytes)+len(elseBranch)+8)) // +8 for the size of the jump location itself
	}

	bytes = append(bytes, elseBranch...)

	return bytes
}

func (c *compiler) compileFnDef(fnDef parser.FnDef) []byte {
	if fnDef.Stub {
		panic("no stub should be encountered here")
	}

	c.recordExportedFunction(fnDef)

	fnSc := &scopeContext{
		parent:             c.globalScope,
		stackAllocs:        make(map[string]variable),
		currentStackOffset: 0,
	}

	var bytes []byte
	for _, param := range fnDef.Params {
		bytes = append(bytes, fnSc.allocateForType(param.Name, param.Type)...)
	}

	// Compile the function body
	for _, bodyStmt := range fnDef.Body {
		bytes = append(bytes, c.compileStatement(bodyStmt, fnSc, len(bytes))...)
	}

	return bytes
}

func (c *compiler) compileStubDef(stub parser.FnDef) {
	ef := ExportedFunction{
		Name:        stub.Name,
		StartOffset: uint64(len(c.stubs)),
		Params:      make([]FnParam, len(stub.Params)),
		ReturnType:  stub.ReturnType,
		stub:        stub.Stub,
		exported:    stub.Exported,
	}

	for i, arg := range stub.Params {
		ef.Params[i] = FnParam{
			Type: arg.Type,
		}
	}

	c.md.functions = append(c.md.functions, ef)
	c.stubs = append(c.stubs, compiledStub{
		name:   stub.Name,
		number: len(c.stubs),
	})
}

func (c *compiler) recordExportedFunction(fnDef parser.FnDef) {
	if (fnDef.Exported || fnDef.Stub) &&
		fnDef.ReturnType.Kind() == types.KindStruct {
		panic("structs as an exported type is not implemented")

	}

	ef := ExportedFunction{
		Name:        fnDef.Name,
		StartOffset: uint64(len(c.code)),
		Params:      make([]FnParam, len(fnDef.Params)),
		ReturnType:  fnDef.ReturnType,
		stub:        fnDef.Stub,
		exported:    fnDef.Exported,
	}

	for i, arg := range fnDef.Params {
		if (fnDef.Exported || fnDef.Stub) &&
			arg.Type.Kind() == types.KindStruct {
			panic("structs as an exported type is not implemented")
		}

		ef.Params[i] = FnParam{
			Type: arg.Type,
		}
	}

	c.md.functions = append(c.md.functions, ef)
}

func (c *compiler) recordExportedVariable(varDecl parser.VarDecl) {
	ev := ExportedVariable{
		Name:    varDecl.Name,
		Offset:  c.globalScope.stackAllocs[varDecl.Name].stackOffset,
		VarType: varDecl.Type,
	}

	c.md.variables = append(c.md.variables, ev)
}
