package compiler

import (
	"encoding/binary"
	"fmt"
	"leoscript/parser"
)

// The opcodes generated by the compiler
// A number in parentheses in the description indicates a number of arguments that the opcode takes, all 8 bytes long.
// These arguments are later referenced as arg(n) in the description.
const (
	// (1)
	// Push arg1 onto the stack
	OpPush byte = iota + 1
	OpAdd
	OpSub
	OpMul
	OpDiv
	// (1)
	// Store the value at arg1 offset from the stack frame base
	// This is used for local variables in functions
	OpStore
	// (1)
	// Load the variable at arg1 offset from the stack frame base
	// This is used for local variables in functions
	OpLoad
	// (1)
	// Load the variable at arg1 offset from the absolute base of the variable stack
	// This is used for global variables
	OpLoadGlobal
	OpReturn
	OpCall
	// (1)
	// Set the program counter to arg1
	OpJump
	// (1)
	// Set the program counter to arg1 if the top of the stack is 0
	OpJumpIfFalse
	OpEq
	OpLt
	OpGt
	OpLte
	OpGte
	OpAnd
	OpOr
	// (1)
	// Store the value at location arg1 counted from the absolute base of the variable stack
	OpStoreGlobal
)

func Compile(p *parser.Program) *Executable {
	c := &compiler{
		md:   new(Metadata),
		code: make([]byte, 0),
		globalScope: &scopeContext{
			stackAllocs:        make(map[string]variable),
			currentStackOffset: 0,
		},
		functions: make(map[string]uint64),
	}

	// Compile the initialization code required for the program
	for _, stmt := range p.VarDecls {
		c.code = append(c.code, c.compileStatement(stmt, c.globalScope, 0)...)
	}
	// The initialization code is followed by a return to have the VM break out of its execution, allowing it to start acception external invokations.
	c.code = append(c.code, OpReturn) // Add a return at the end of the program

	for _, fnDef := range p.FnDefs {
		c.functions[fnDef.Name] = uint64(len(c.code))
		c.code = append(c.code, c.compileFnDef(fnDef)...)
	}

	for _, fn := range c.unresolvedFunctions {
		start, ok := c.functions[fn.name]
		if !ok {
			panic(fmt.Sprintf("unresolved function %s not found in functions map", fn.name))
		}
		// Replace the placeholder offset with the actual start instruction of the function
		binary.BigEndian.PutUint64(c.code[fn.placeholderOffset:], start)
	}

	return &Executable{
		md:   c.md,
		code: c.code,
	}
}

type Executable struct {
	md   *Metadata
	code []byte
}

func (e *Executable) Marshal() []byte {
	return append(e.md.Marshal(), e.code...)
}

func (e *Executable) Metadata() *Metadata {
	return e.md
}

func (e *Executable) Code() []byte {
	return e.code
}

func (e *Executable) Unmarshal(raw []byte) error {
	if len(raw) < 8 {
		return fmt.Errorf("raw executable is too short")
	}

	e.md = new(Metadata)

	mdSize := binary.BigEndian.Uint64(raw[:8])
	if err := e.md.Unmarshal(raw[0 : mdSize+8]); err != nil {
		return fmt.Errorf("unmarshalling metadata: %w", err)
	}

	e.code = raw[mdSize+8:]
	return nil
}

type scopeContext struct {
	parent *scopeContext
	// The stack offsets for each variable allocated on the stack
	stackAllocs map[string]variable
	// The current stack offset for the next variable to be allocated
	currentStackOffset uint64
}

func (sc *scopeContext) allocateVariable(name string) {
	if _, exists := sc.stackAllocs[name]; exists {
		panic(fmt.Sprintf("variable %s already exists in scope", name))
	}
	sc.stackAllocs[name] = variable{
		stackOffset: sc.currentStackOffset,
	}
	sc.currentStackOffset += 8
}

func (sc *scopeContext) getVariable(name string) (variable, bool) {
	v, ok := sc.stackAllocs[name]
	if ok {
		return v, true
	}

	if sc.parent != nil {
		return sc.parent.getVariable(name)
	}

	return variable{}, false
}

type variable struct {
	stackOffset uint64
	// size        uint64
}

type compiler struct {
	md   *Metadata
	code []byte

	// A mapping for the start-instruction of each function
	functions map[string]uint64

	globalScope *scopeContext

	unresolvedFunctions []unresolvedFunction
}

// unresolvedFunction is used to track a function call that has not yet been compiled and therefore does not have a start instruction.
type unresolvedFunction struct {
	name              string
	placeholderOffset uint64 // The offset in the code where the function call is made
}

func CompileStatement(stmt parser.Statement) []byte {
	c := &compiler{
		md:          new(Metadata),
		code:        make([]byte, 0),
		globalScope: nil,
		functions:   make(map[string]uint64),
	}
	c.code = append(c.code, c.compileStatement(stmt, &scopeContext{
		stackAllocs:        make(map[string]variable),
		currentStackOffset: 0,
	}, 0)...)
	return c.code
}

func (c *compiler) compileStatement(stmt parser.Statement, sc *scopeContext, pendingBytes int) []byte {
	var bytes []byte // TODO: Possible optimization to pre-allocate the size of bytes based on the expected size of the type of stmt

	switch stmt := stmt.(type) {
	case parser.IntegerLiteral:
		bytes = append(bytes, OpPush)
		bytes = binary.BigEndian.AppendUint64(bytes, uint64(stmt.Value))
	case parser.BooleanLiteral:
		bytes = append(bytes, OpPush)
		if stmt.Value {
			bytes = binary.BigEndian.AppendUint64(bytes, 1) // true
		} else {
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // false
		}
	case parser.VoidLiteral:
		// No operation needed for void literals
	case parser.UnaryExpression:
		switch stmt.Op {
		case "-":
			bytes = append(bytes, OpPush)
			bytes = binary.BigEndian.AppendUint64(bytes, 0)

			bytes = append(bytes, OpPush)
			expr := c.compileStatement(stmt.Expression, sc, 0)
			bytes = append(bytes, expr...)

			bytes = append(bytes, OpSub)
		case "!":
			expr := c.compileStatement(stmt.Expression, sc, 0)
			bytes = append(bytes, expr...)
			bytes = append(bytes, OpPush)
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // Push false
			bytes = append(bytes, OpEq)                     // Negate the result of equality
		default:
			panic("unsupported unary operator: " + stmt.Op)
		}
	case parser.BinaryExpression:
		left := c.compileStatement(stmt.Left, sc, 0)
		right := c.compileStatement(stmt.Right, sc, 0)

		bytes = append(bytes, left...)
		bytes = append(bytes, right...)

		switch stmt.Op {
		case "+":
			bytes = append(bytes, OpAdd)
		case "-":
			bytes = append(bytes, OpSub)
		case "*":
			bytes = append(bytes, OpMul)
		case "/":
			bytes = append(bytes, OpDiv)
		case "==":
			bytes = append(bytes, OpEq)
		case "<":
			bytes = append(bytes, OpLt)
		case ">":
			bytes = append(bytes, OpGt)
		case "<=":
			bytes = append(bytes, OpLte)
		case ">=":
			bytes = append(bytes, OpGte)
		case "!=":
			// For !=, we can use the equality operator and negate the result
			bytes = append(bytes, OpEq)
			bytes = append(bytes, OpPush)
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // Push false
			bytes = append(bytes, OpEq)                     // Negate the result of equality
		case "&&": // TODO: Short-circuit evaluation
			bytes = append(bytes, OpAnd)
		case "||": // TODO: Short-circuit evaluation
			bytes = append(bytes, OpOr)
		default:
			panic("unsupported binary operator: " + stmt.Op)
		}
	case parser.VarDecl:
		// The code required to compute the value of the variable.
		val := c.compileStatement(stmt.Value, sc, 0)

		bytes = append(bytes, val...)

		// If the variable is a global variable, we need to store it in the global scope
		if sc == c.globalScope {
			bytes = append(bytes, OpStoreGlobal)
		} else {
			bytes = append(bytes, OpStore)
		}
		bytes = binary.BigEndian.AppendUint64(bytes, sc.currentStackOffset)

		// The full size required by the variable
		sc.allocateVariable(stmt.Name)

		if stmt.Exported {
			c.recordExportedVariable(stmt)
		}

	case parser.VarIdentifier:
		v, ok := sc.getVariable(stmt.Name)
		if ok && sc == c.globalScope {
			bytes = append(bytes, OpLoadGlobal)
		} else if ok {
			bytes = append(bytes, OpLoad)
		} else {
			v, ok = c.globalScope.getVariable(stmt.Name)
			if !ok {
				panic(fmt.Sprintf("variable %s not found in scope", stmt.Name))
			}

			bytes = append(bytes, OpLoadGlobal)
		}

		// bytes = binary.BigEndian.AppendUint64(bytes, v.size)
		bytes = binary.BigEndian.AppendUint64(bytes, v.stackOffset)
	case parser.Return:
		if stmt.Value != nil {
			val := c.compileStatement(stmt.Value, sc, 0)
			bytes = append(bytes, val...)
		}
		bytes = append(bytes, OpReturn)
	case parser.Call:
		// Compile the function call arguments
		for _, arg := range stmt.Args {
			argBytes := c.compileStatement(arg, sc, len(bytes))
			bytes = append(bytes, argBytes...)
		}

		bytes = append(bytes, OpCall)

		// Call the function
		start, ok := c.functions[stmt.Name]
		if ok {
			bytes = binary.BigEndian.AppendUint64(bytes, start)
		} else {
			// If the function is not defined yet, we need to add a placeholder for it
			c.unresolvedFunctions = append(c.unresolvedFunctions, unresolvedFunction{
				name:              stmt.Name,
				placeholderOffset: uint64(len(c.code) + len(bytes)),
			})
			bytes = binary.BigEndian.AppendUint64(bytes, 0) // Placeholder for the function call
		}
	case parser.If:
		bytes = c.compileIf(stmt, sc, pendingBytes)
	case parser.Assignment:
		// Compile the value to assign
		val := c.compileStatement(stmt.Value, sc, 0)
		bytes = append(bytes, val...)

		// Find the variable to assign to
		v, ok := sc.getVariable(stmt.Name)
		if ok && sc == c.globalScope {
			bytes = append(bytes, OpStoreGlobal)
		} else if ok {
			bytes = append(bytes, OpStore)
		} else {
			v, ok = c.globalScope.getVariable(stmt.Name)
			if !ok {
				panic(fmt.Sprintf("variable %s not found in scope", stmt.Name))
			}

			bytes = append(bytes, OpStoreGlobal)
		}

		bytes = binary.BigEndian.AppendUint64(bytes, v.stackOffset)
	default:
		panic(fmt.Sprintf("unsupported statement type: %T", stmt))
	}

	return bytes
}

func (c *compiler) compileIf(ifStmt parser.If, sc *scopeContext, pendingBytes int) []byte {
	var bytes []byte
	// Compile the condition
	cond := c.compileStatement(ifStmt.Cond, sc, 0)
	bytes = append(bytes, cond...)

	// Compile the true branch
	var trueBranch []byte
	for _, trueStmt := range ifStmt.Then {
		subStack := &scopeContext{
			parent:             sc,
			stackAllocs:        make(map[string]variable),
			currentStackOffset: sc.currentStackOffset,
		}

		trueBranch = append(trueBranch, c.compileStatement(trueStmt, subStack, len(bytes))...)
	}

	var elseBranch []byte
	for _, elseStmt := range ifStmt.Else {
		subStack := &scopeContext{
			parent:             sc,
			stackAllocs:        make(map[string]variable),
			currentStackOffset: sc.currentStackOffset,
		}

		elseBranch = append(elseBranch, c.compileStatement(elseStmt, subStack, len(bytes))...)
	}

	bytes = append(bytes, OpJumpIfFalse)

	// The offset to jump to if the condition is false
	var falseOffset uint64
	if len(elseBranch) > 0 {
		// If there is an else branch, we need to jump to it if the condition is false
		falseOffset = uint64(len(c.code) + pendingBytes + len(bytes) + len(trueBranch) + 8) // +8 for the size of the jump location itself
		bytes = binary.BigEndian.AppendUint64(bytes, falseOffset)
	} else {
		// If there is no else branch, we just jump over the true branch
		falseOffset = uint64(len(c.code) + pendingBytes + len(bytes) + len(trueBranch) + 8) // +8 for the size of the jump location itself
		bytes = binary.BigEndian.AppendUint64(bytes, falseOffset)
	}

	bytes = append(bytes, trueBranch...)

	if len(elseBranch) > 0 {
		// If there is an else branch, we need to jump over it after the true branch
		bytes = append(bytes, OpJump)
		// The offset to jump to after the true branch
		bytes = binary.BigEndian.AppendUint64(bytes, uint64(len(c.code)+pendingBytes+len(bytes)+len(elseBranch)+8)) // +8 for the size of the jump location itself
	}

	bytes = append(bytes, elseBranch...)

	return bytes
}

func (c *compiler) compileFnDef(fnDef parser.FnDef) []byte {
	if fnDef.Stub {
		panic("stubs not implemented")
	}

	c.recordExportedFunction(fnDef)

	var bytes []byte

	fnSc := &scopeContext{
		stackAllocs:        make(map[string]variable),
		currentStackOffset: 0,
	}

	for _, arg := range fnDef.Args {
		// Allocate space for each parameter in the stack
		bytes = append(bytes, OpStore)
		bytes = binary.BigEndian.AppendUint64(bytes, fnSc.currentStackOffset)
		fnSc.allocateVariable(arg.Name)
	}

	// Compile the function body
	for _, bodyStmt := range fnDef.Body {
		bytes = append(bytes, c.compileStatement(bodyStmt, fnSc, len(bytes))...)
	}

	return bytes
}

func (c *compiler) recordExportedFunction(fnDef parser.FnDef) {
	ef := exportedFunction{
		name:        fnDef.Name,
		startOffset: uint64(len(c.code)),
		args:        make([]fnArg, len(fnDef.Args)),
		returnType:  fnDef.ReturnType,
		stub:        fnDef.Stub,
		exported:    fnDef.Exported,
	}

	for i, arg := range fnDef.Args {
		ef.args[i] = fnArg{
			argType: arg.Type,
		}
	}

	c.md.functions = append(c.md.functions, ef)
}

func (c *compiler) recordExportedVariable(varDecl parser.VarDecl) {
	ev := exportedVariable{
		name:    varDecl.Name,
		offset:  c.globalScope.stackAllocs[varDecl.Name].stackOffset,
		varType: varDecl.Type,
	}

	c.md.variables = append(c.md.variables, ev)
}
